import { Tempo } from '../model/tempo';

export class ConstantVariables {

    waveVelocity: number = 299792458;

    toSamplesDivisor: number = 27682;

    noteStrings: any = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'];

    tempos = new Array<Tempo>(
        { tipo: 'semibreve', tempo: null, power: 64, tabDelimiter: 7 },
        { tipo: 'minima', tempo: null, power: 32, tabDelimiter: 6 },
        { tipo: 'semiminima', tempo: null, power: 16, tabDelimiter: 5 },
        { tipo: 'colcheia', tempo: null, power: 8, tabDelimiter: 4 },
        { tipo: 'semicolcheia', tempo: null, power: 4, tabDelimiter: 3 },
        { tipo: 'fusa', tempo: null, power: 2, tabDelimiter: 2 },
        { tipo: 'semifusa', tempo: null, power: 1, tabDelimiter: 1 });

    casas = new Array(
        { corda: 4, casa: 0, frequencia: 41 },
        { corda: 4, casa: 1, frequencia: 44 },
        { corda: 4, casa: 2, frequencia: 46 },
        { corda: 4, casa: 3, frequencia: 49 },
        { corda: 4, casa: 4, frequencia: 52 },
        { corda: 4, casa: 5, frequencia: 55 },
        { corda: 4, casa: 6, frequencia: 58 },
        { corda: 4, casa: 7, frequencia: 62 },
        { corda: 4, casa: 8, frequencia: 65 },
        { corda: 4, casa: 9, frequencia: 69 },
        { corda: 4, casa: 10, frequencia: 73 },
        { corda: 4, casa: 11, frequencia: 78 },
        { corda: 4, casa: 12, frequencia: 82 },
        { corda: 4, casa: 13, frequencia: 87 },
        { corda: 4, casa: 14, frequencia: 92 },
        { corda: 4, casa: 15, frequencia: 98 },
        { corda: 4, casa: 16, frequencia: 104 },
        { corda: 4, casa: 17, frequencia: 110 },
        { corda: 4, casa: 18, frequencia: 117 },
        { corda: 4, casa: 19, frequencia: 123 },
        { corda: 4, casa: 20, frequencia: 131 },
        { corda: 3, casa: 0, frequencia: 55 },
        { corda: 3, casa: 1, frequencia: 58 },
        { corda: 3, casa: 2, frequencia: 62 },
        { corda: 3, casa: 3, frequencia: 65 },
        { corda: 3, casa: 4, frequencia: 69 },
        { corda: 3, casa: 5, frequencia: 73 },
        { corda: 3, casa: 6, frequencia: 78 },
        { corda: 3, casa: 7, frequencia: 82 },
        { corda: 3, casa: 8, frequencia: 87 },
        { corda: 3, casa: 9, frequencia: 92 },
        { corda: 3, casa: 10, frequencia: 98 },
        { corda: 3, casa: 11, frequencia: 104 },
        { corda: 3, casa: 12, frequencia: 110 },
        { corda: 3, casa: 13, frequencia: 117 },
        { corda: 3, casa: 14, frequencia: 123 },
        { corda: 3, casa: 15, frequencia: 131 },
        { corda: 3, casa: 16, frequencia: 139 },
        { corda: 3, casa: 17, frequencia: 147 },
        { corda: 3, casa: 18, frequencia: 156 },
        { corda: 3, casa: 19, frequencia: 165 },
        { corda: 3, casa: 20, frequencia: 175 },
        { corda: 2, casa: 0, frequencia: 73 },
        { corda: 2, casa: 1, frequencia: 78 },
        { corda: 2, casa: 2, frequencia: 82 },
        { corda: 2, casa: 3, frequencia: 87 },
        { corda: 2, casa: 4, frequencia: 92 },
        { corda: 2, casa: 5, frequencia: 98 },
        { corda: 2, casa: 6, frequencia: 104 },
        { corda: 2, casa: 7, frequencia: 110 },
        { corda: 2, casa: 8, frequencia: 117 },
        { corda: 2, casa: 9, frequencia: 123 },
        { corda: 2, casa: 10, frequencia: 131 },
        { corda: 2, casa: 11, frequencia: 139 },
        { corda: 2, casa: 12, frequencia: 147 },
        { corda: 2, casa: 13, frequencia: 156 },
        { corda: 2, casa: 14, frequencia: 165 },
        { corda: 2, casa: 15, frequencia: 175 },
        { corda: 2, casa: 16, frequencia: 185 },
        { corda: 2, casa: 17, frequencia: 196 },
        { corda: 2, casa: 18, frequencia: 208 },
        { corda: 2, casa: 19, frequencia: 220 },
        { corda: 2, casa: 20, frequencia: 233 },
        { corda: 1, casa: 0, frequencia: 98 },
        { corda: 1, casa: 1, frequencia: 104 },
        { corda: 1, casa: 2, frequencia: 110 },
        { corda: 1, casa: 3, frequencia: 117 },
        { corda: 1, casa: 4, frequencia: 123 },
        { corda: 1, casa: 5, frequencia: 131 },
        { corda: 1, casa: 6, frequencia: 139 },
        { corda: 1, casa: 7, frequencia: 147 },
        { corda: 1, casa: 8, frequencia: 156 },
        { corda: 1, casa: 9, frequencia: 165 },
        { corda: 1, casa: 10, frequencia: 175 },
        { corda: 1, casa: 11, frequencia: 185 },
        { corda: 1, casa: 12, frequencia: 196 },
        { corda: 1, casa: 13, frequencia: 208 },
        { corda: 1, casa: 14, frequencia: 220 },
        { corda: 1, casa: 15, frequencia: 233 },
        { corda: 1, casa: 16, frequencia: 247 },
        { corda: 1, casa: 17, frequencia: 262 },
        { corda: 1, casa: 18, frequencia: 277 },
        { corda: 1, casa: 19, frequencia: 294 },
        { corda: 1, casa: 20, frequencia: 311 });
}
